export type ToolCategory =
  | "organize"
  | "optimize"
  | "convert"
  | "edit"
  | "forms"
  | "esign"
  | "security"
  | "ocr"
  | "compare"
  | "ai";

export type ComplexityClass = "L" | "M" | "H";
export type MinTier = "free" | "plus" | "pro" | "pro_ai" | "esign_addon";

export interface ToolDefinition {
  slug: string;
  name: string;
  description: string;
  category: ToolCategory;
  icon: string; // Lucide icon name
  color: string; // Tailwind color class
  complexity: ComplexityClass;
  creditCost: string;
  minTier: MinTier;
  acceptedTypes: string[];
  multiFile: boolean;
  maxFiles: number;
  outputFormat: string;
  implemented: boolean;
}

export const CATEGORY_META: Record<
  ToolCategory,
  { label: string; description: string; color: string; gradient: string }
> = {
  organize: {
    label: "Organize & Pages",
    description: "Merge, split, reorder, rotate, and extract pages",
    color: "text-blue-600",
    gradient: "from-blue-500 to-blue-600",
  },
  optimize: {
    label: "Optimize & Repair",
    description: "Compress, repair, and optimize PDFs for web",
    color: "text-emerald-600",
    gradient: "from-emerald-500 to-emerald-600",
  },
  convert: {
    label: "Convert",
    description: "Convert between PDF, Office, images, and more",
    color: "text-orange-600",
    gradient: "from-orange-500 to-orange-600",
  },
  edit: {
    label: "Edit & Annotate",
    description: "Mark up, edit text, and add links to PDFs",
    color: "text-purple-600",
    gradient: "from-purple-500 to-purple-600",
  },
  forms: {
    label: "Forms",
    description: "Fill and create PDF form fields",
    color: "text-pink-600",
    gradient: "from-pink-500 to-pink-600",
  },
  esign: {
    label: "E-Signature",
    description: "Sign documents and send for signature",
    color: "text-indigo-600",
    gradient: "from-indigo-500 to-indigo-600",
  },
  security: {
    label: "Security & Compliance",
    description: "Protect, unlock, redact, watermark, and sanitize",
    color: "text-red-600",
    gradient: "from-red-500 to-red-600",
  },
  ocr: {
    label: "OCR & Extraction",
    description: "Make scanned PDFs searchable and extract data",
    color: "text-amber-600",
    gradient: "from-amber-500 to-amber-600",
  },
  compare: {
    label: "Compare",
    description: "Compare two PDFs side by side",
    color: "text-cyan-600",
    gradient: "from-cyan-500 to-cyan-600",
  },
  ai: {
    label: "AI Tools",
    description: "Chat with, summarize, and translate PDFs using AI",
    color: "text-violet-600",
    gradient: "from-violet-500 to-violet-600",
  },
};

export const TOOLS: ToolDefinition[] = [
  // ─── A. Organize & Page Operations ───
  {
    slug: "merge-pdf",
    name: "Merge PDF",
    description:
      "Combine multiple PDF files into a single document. Reorder, interleave, and control bookmark handling.",
    category: "organize",
    icon: "Layers",
    color: "bg-blue-500",
    complexity: "L",
    creditCost: "1 credit/output page",
    minTier: "free",
    acceptedTypes: [".pdf", ".jpg", ".jpeg", ".png"],
    multiFile: true,
    maxFiles: 20,
    outputFormat: "pdf",
    implemented: true,
  },
  {
    slug: "split-pdf",
    name: "Split PDF",
    description:
      "Split a PDF by page ranges, extract specific pages, or split into individual pages.",
    category: "organize",
    icon: "Scissors",
    color: "bg-blue-400",
    complexity: "L",
    creditCost: "1 credit/output page",
    minTier: "free",
    acceptedTypes: [".pdf"],
    multiFile: false,
    maxFiles: 1,
    outputFormat: "pdf/zip",
    implemented: true,
  },
  {
    slug: "organize-pages",
    name: "Organize Pages",
    description:
      "Reorder, delete, duplicate, and insert pages with a visual drag-and-drop interface.",
    category: "organize",
    icon: "LayoutGrid",
    color: "bg-blue-600",
    complexity: "L",
    creditCost: "1 credit/page changed (min 5)",
    minTier: "free",
    acceptedTypes: [".pdf"],
    multiFile: false,
    maxFiles: 1,
    outputFormat: "pdf",
    implemented: true,
  },
  {
    slug: "rotate-pdf",
    name: "Rotate Pages",
    description:
      "Rotate selected pages 90, 180, or 270 degrees. Fix incorrectly oriented scans instantly.",
    category: "organize",
    icon: "RotateCw",
    color: "bg-blue-300",
    complexity: "L",
    creditCost: "0.25 credit/page (min 2)",
    minTier: "free",
    acceptedTypes: [".pdf"],
    multiFile: false,
    maxFiles: 1,
    outputFormat: "pdf",
    implemented: true,
  },
  {
    slug: "crop-pdf",
    name: "Crop / Trim Margins",
    description:
      "Crop page margins or auto-detect content boundaries to remove whitespace.",
    category: "organize",
    icon: "Crop",
    color: "bg-blue-700",
    complexity: "M",
    creditCost: "1.5 credits/page",
    minTier: "pro",
    acceptedTypes: [".pdf"],
    multiFile: false,
    maxFiles: 1,
    outputFormat: "pdf",
    implemented: false,
  },
  {
    slug: "extract-pages",
    name: "Extract Pages",
    description:
      "Pull specific pages into a new PDF or extract all embedded images from a document.",
    category: "organize",
    icon: "FileOutput",
    color: "bg-blue-500",
    complexity: "L",
    creditCost: "1 credit/page",
    minTier: "free",
    acceptedTypes: [".pdf"],
    multiFile: false,
    maxFiles: 1,
    outputFormat: "pdf/zip",
    implemented: true,
  },
  // ─── B. Optimize & Repair ───
  {
    slug: "compress-pdf",
    name: "Compress PDF",
    description:
      "Reduce PDF file size while maintaining quality. Choose Basic or Strong compression.",
    category: "optimize",
    icon: "Minimize2",
    color: "bg-emerald-500",
    complexity: "M",
    creditCost: "2–3.5 credits/page",
    minTier: "free",
    acceptedTypes: [".pdf"],
    multiFile: false,
    maxFiles: 1,
    outputFormat: "pdf",
    implemented: true,
  },
  {
    slug: "repair-pdf",
    name: "Repair PDF",
    description:
      "Attempt to fix corrupted PDFs by rebuilding cross-reference tables and recovering pages.",
    category: "optimize",
    icon: "Wrench",
    color: "bg-emerald-600",
    complexity: "H",
    creditCost: "50 + 2 credits/page recovered",
    minTier: "pro",
    acceptedTypes: [".pdf"],
    multiFile: false,
    maxFiles: 1,
    outputFormat: "pdf",
    implemented: false,
  },
  {
    slug: "optimize-web",
    name: "Optimize for Web",
    description:
      "Linearize PDFs for fast web viewing. Pages load progressively in browsers.",
    category: "optimize",
    icon: "Globe",
    color: "bg-emerald-400",
    complexity: "M",
    creditCost: "1 credit/page",
    minTier: "free",
    acceptedTypes: [".pdf"],
    multiFile: false,
    maxFiles: 1,
    outputFormat: "pdf",
    implemented: false,
  },
  // ─── C. Convert ───
  {
    slug: "pdf-to-word",
    name: "PDF to Word",
    description:
      "Convert PDF to editable DOCX. Choose layout-preserving or text-first mode.",
    category: "convert",
    icon: "FileText",
    color: "bg-orange-500",
    complexity: "H",
    creditCost: "4–6 credits/page",
    minTier: "pro",
    acceptedTypes: [".pdf"],
    multiFile: false,
    maxFiles: 1,
    outputFormat: "docx",
    implemented: false,
  },
  {
    slug: "pdf-to-excel",
    name: "PDF to Excel",
    description:
      "Extract tables from PDF into editable XLSX spreadsheets.",
    category: "convert",
    icon: "Table",
    color: "bg-orange-600",
    complexity: "H",
    creditCost: "4–6 credits/page",
    minTier: "pro",
    acceptedTypes: [".pdf"],
    multiFile: false,
    maxFiles: 1,
    outputFormat: "xlsx",
    implemented: false,
  },
  {
    slug: "pdf-to-powerpoint",
    name: "PDF to PowerPoint",
    description:
      "Convert PDF slides into editable PPTX presentations.",
    category: "convert",
    icon: "Presentation",
    color: "bg-orange-400",
    complexity: "H",
    creditCost: "4–6 credits/page",
    minTier: "pro",
    acceptedTypes: [".pdf"],
    multiFile: false,
    maxFiles: 1,
    outputFormat: "pptx",
    implemented: false,
  },
  {
    slug: "pdf-to-images",
    name: "PDF to Images",
    description:
      "Convert PDF pages to high-quality JPG or PNG images at your chosen resolution.",
    category: "convert",
    icon: "Image",
    color: "bg-orange-500",
    complexity: "M",
    creditCost: "2 credits/page",
    minTier: "free",
    acceptedTypes: [".pdf"],
    multiFile: false,
    maxFiles: 1,
    outputFormat: "jpg/png/zip",
    implemented: true,
  },
  {
    slug: "images-to-pdf",
    name: "Images to PDF",
    description:
      "Combine JPG, PNG, or other images into a single PDF document.",
    category: "convert",
    icon: "ImagePlus",
    color: "bg-orange-300",
    complexity: "M",
    creditCost: "1 credit/image",
    minTier: "free",
    acceptedTypes: [".jpg", ".jpeg", ".png", ".webp", ".tiff", ".heic"],
    multiFile: true,
    maxFiles: 50,
    outputFormat: "pdf",
    implemented: true,
  },
  {
    slug: "pdf-to-pdfa",
    name: "PDF to PDF/A",
    description:
      "Convert to archival-standard PDF/A for long-term preservation and compliance.",
    category: "convert",
    icon: "Archive",
    color: "bg-orange-700",
    complexity: "H",
    creditCost: "5 credits/page",
    minTier: "pro",
    acceptedTypes: [".pdf"],
    multiFile: false,
    maxFiles: 1,
    outputFormat: "pdf",
    implemented: false,
  },
  {
    slug: "office-to-pdf",
    name: "Office to PDF",
    description:
      "Convert Word, Excel, and PowerPoint files to PDF format.",
    category: "convert",
    icon: "FileUp",
    color: "bg-orange-600",
    complexity: "H",
    creditCost: "5 credits/page",
    minTier: "pro",
    acceptedTypes: [".docx", ".xlsx", ".pptx"],
    multiFile: false,
    maxFiles: 1,
    outputFormat: "pdf",
    implemented: false,
  },
  {
    slug: "html-to-pdf",
    name: "HTML to PDF",
    description: "Convert web pages or HTML files to PDF documents.",
    category: "convert",
    icon: "Code",
    color: "bg-orange-500",
    complexity: "H",
    creditCost: "5 credits/page",
    minTier: "pro",
    acceptedTypes: [".html", ".htm"],
    multiFile: false,
    maxFiles: 1,
    outputFormat: "pdf",
    implemented: false,
  },
  // ─── D. Edit & Annotate ───
  {
    slug: "annotate-pdf",
    name: "Annotate PDF",
    description:
      "Add highlights, underlines, shapes, sticky notes, and freehand drawings.",
    category: "edit",
    icon: "Highlighter",
    color: "bg-purple-500",
    complexity: "M",
    creditCost: "2 credits/page modified",
    minTier: "free",
    acceptedTypes: [".pdf"],
    multiFile: false,
    maxFiles: 1,
    outputFormat: "pdf",
    implemented: false,
  },
  {
    slug: "edit-pdf",
    name: "Edit PDF Text",
    description:
      "Edit existing text and replace images directly inside your PDF.",
    category: "edit",
    icon: "PenLine",
    color: "bg-purple-600",
    complexity: "H",
    creditCost: "6 credits/page modified",
    minTier: "pro",
    acceptedTypes: [".pdf"],
    multiFile: false,
    maxFiles: 1,
    outputFormat: "pdf",
    implemented: false,
  },
  {
    slug: "add-links",
    name: "Add Links",
    description:
      "Insert clickable hyperlinks and internal navigation links into your PDF.",
    category: "edit",
    icon: "Link",
    color: "bg-purple-400",
    complexity: "M",
    creditCost: "2 credits/page",
    minTier: "free",
    acceptedTypes: [".pdf"],
    multiFile: false,
    maxFiles: 1,
    outputFormat: "pdf",
    implemented: false,
  },
  // ─── E. Forms ───
  {
    slug: "fill-forms",
    name: "Fill PDF Forms",
    description:
      "Fill in interactive PDF form fields and optionally flatten them.",
    category: "forms",
    icon: "ClipboardEdit",
    color: "bg-pink-500",
    complexity: "M",
    creditCost: "2 credits/page with fields",
    minTier: "free",
    acceptedTypes: [".pdf"],
    multiFile: false,
    maxFiles: 1,
    outputFormat: "pdf",
    implemented: false,
  },
  {
    slug: "create-forms",
    name: "Create Form Fields",
    description:
      "Add text inputs, checkboxes, dropdowns, and signature fields to any PDF.",
    category: "forms",
    icon: "FormInput",
    color: "bg-pink-600",
    complexity: "H",
    creditCost: "40 + 1 credit/page",
    minTier: "pro",
    acceptedTypes: [".pdf"],
    multiFile: false,
    maxFiles: 1,
    outputFormat: "pdf",
    implemented: false,
  },
  // ─── F. E-Signature ───
  {
    slug: "sign-pdf",
    name: "Sign PDF",
    description:
      "Add your signature to any PDF. Draw, type, or upload your signature.",
    category: "esign",
    icon: "Pen",
    color: "bg-indigo-500",
    complexity: "M",
    creditCost: "10 credits/document",
    minTier: "free",
    acceptedTypes: [".pdf"],
    multiFile: false,
    maxFiles: 1,
    outputFormat: "pdf",
    implemented: false,
  },
  {
    slug: "request-signatures",
    name: "Request Signatures",
    description:
      "Send documents for signature with workflows, reminders, and audit trails.",
    category: "esign",
    icon: "Send",
    color: "bg-indigo-600",
    complexity: "H",
    creditCost: "60 + 2 credits/page",
    minTier: "esign_addon",
    acceptedTypes: [".pdf"],
    multiFile: false,
    maxFiles: 1,
    outputFormat: "pdf",
    implemented: false,
  },
  // ─── G. Security & Compliance ───
  {
    slug: "protect-pdf",
    name: "Protect PDF",
    description:
      "Add password protection and restrict printing, copying, or editing.",
    category: "security",
    icon: "Lock",
    color: "bg-red-500",
    complexity: "M",
    creditCost: "2 credits/page",
    minTier: "free",
    acceptedTypes: [".pdf"],
    multiFile: false,
    maxFiles: 1,
    outputFormat: "pdf",
    implemented: true,
  },
  {
    slug: "unlock-pdf",
    name: "Unlock PDF",
    description:
      "Remove password protection from a PDF when you have the password.",
    category: "security",
    icon: "Unlock",
    color: "bg-red-400",
    complexity: "M",
    creditCost: "2 credits/page",
    minTier: "free",
    acceptedTypes: [".pdf"],
    multiFile: false,
    maxFiles: 1,
    outputFormat: "pdf",
    implemented: true,
  },
  {
    slug: "redact-pdf",
    name: "Redact PDF",
    description:
      "Permanently remove sensitive content. Search and redact text patterns across pages.",
    category: "security",
    icon: "EyeOff",
    color: "bg-red-700",
    complexity: "H",
    creditCost: "6 credits/page + 10/pattern",
    minTier: "pro",
    acceptedTypes: [".pdf"],
    multiFile: false,
    maxFiles: 1,
    outputFormat: "pdf",
    implemented: false,
  },
  {
    slug: "watermark-pdf",
    name: "Add Watermark",
    description:
      "Add text or image watermarks with custom opacity, rotation, and positioning.",
    category: "security",
    icon: "Stamp",
    color: "bg-red-500",
    complexity: "M",
    creditCost: "2 credits/page",
    minTier: "free",
    acceptedTypes: [".pdf"],
    multiFile: false,
    maxFiles: 1,
    outputFormat: "pdf",
    implemented: true,
  },
  {
    slug: "page-numbers",
    name: "Add Page Numbers",
    description:
      "Insert page numbers with custom format, position, and starting number.",
    category: "security",
    icon: "Hash",
    color: "bg-red-400",
    complexity: "M",
    creditCost: "1.5 credits/page",
    minTier: "free",
    acceptedTypes: [".pdf"],
    multiFile: false,
    maxFiles: 1,
    outputFormat: "pdf",
    implemented: true,
  },
  {
    slug: "pdf-metadata",
    name: "Edit Metadata",
    description:
      "View, edit, or remove PDF metadata. Sanitize hidden data and embedded scripts.",
    category: "security",
    icon: "FileSearch",
    color: "bg-red-600",
    complexity: "M",
    creditCost: "2 credits/page",
    minTier: "free",
    acceptedTypes: [".pdf"],
    multiFile: false,
    maxFiles: 1,
    outputFormat: "pdf",
    implemented: true,
  },
  // ─── H. OCR & Extraction ───
  {
    slug: "ocr-pdf",
    name: "OCR PDF",
    description:
      "Make scanned PDFs searchable by adding an invisible text layer via OCR.",
    category: "ocr",
    icon: "ScanText",
    color: "bg-amber-500",
    complexity: "H",
    creditCost: "8 credits/page",
    minTier: "pro",
    acceptedTypes: [".pdf", ".jpg", ".jpeg", ".png", ".tiff"],
    multiFile: false,
    maxFiles: 1,
    outputFormat: "pdf",
    implemented: false,
  },
  {
    slug: "extract-text",
    name: "Extract Text & Tables",
    description:
      "Extract raw text or structured table data into TXT, JSON, CSV, or XLSX.",
    category: "ocr",
    icon: "FileSpreadsheet",
    color: "bg-amber-600",
    complexity: "H",
    creditCost: "4 credits/page",
    minTier: "pro",
    acceptedTypes: [".pdf"],
    multiFile: false,
    maxFiles: 1,
    outputFormat: "txt/csv/xlsx",
    implemented: false,
  },
  // ─── I. Compare ───
  {
    slug: "compare-pdf",
    name: "Compare PDFs",
    description:
      "Compare two PDFs and generate a visual diff report highlighting all changes.",
    category: "compare",
    icon: "GitCompare",
    color: "bg-cyan-500",
    complexity: "H",
    creditCost: "10 credits/page compared",
    minTier: "pro",
    acceptedTypes: [".pdf"],
    multiFile: true,
    maxFiles: 2,
    outputFormat: "pdf",
    implemented: false,
  },
  // ─── J. AI Tools ───
  {
    slug: "chat-with-pdf",
    name: "Chat with PDF",
    description:
      "Ask questions about your PDF and get instant AI-powered answers.",
    category: "ai",
    icon: "MessageSquare",
    color: "bg-violet-500",
    complexity: "H",
    creditCost: "1 AI credit/question",
    minTier: "pro_ai",
    acceptedTypes: [".pdf"],
    multiFile: false,
    maxFiles: 1,
    outputFormat: "text",
    implemented: false,
  },
  {
    slug: "summarize-pdf",
    name: "Summarize PDF",
    description:
      "Get an AI-generated summary of your document in seconds.",
    category: "ai",
    icon: "Sparkles",
    color: "bg-violet-600",
    complexity: "H",
    creditCost: "5–20 AI credits",
    minTier: "pro_ai",
    acceptedTypes: [".pdf"],
    multiFile: false,
    maxFiles: 1,
    outputFormat: "text",
    implemented: false,
  },
  {
    slug: "translate-pdf",
    name: "Translate PDF",
    description:
      "Translate your PDF into another language while preserving the layout.",
    category: "ai",
    icon: "Languages",
    color: "bg-violet-400",
    complexity: "H",
    creditCost: "2 AI credits/page",
    minTier: "pro_ai",
    acceptedTypes: [".pdf"],
    multiFile: false,
    maxFiles: 1,
    outputFormat: "pdf",
    implemented: false,
  },
];

export function getToolBySlug(slug: string): ToolDefinition | undefined {
  return TOOLS.find((t) => t.slug === slug);
}

export function getToolsByCategory(category: ToolCategory): ToolDefinition[] {
  return TOOLS.filter((t) => t.category === category);
}

export function getImplementedTools(): ToolDefinition[] {
  return TOOLS.filter((t) => t.implemented);
}

export const CATEGORY_ORDER: ToolCategory[] = [
  "organize",
  "optimize",
  "convert",
  "edit",
  "forms",
  "esign",
  "security",
  "ocr",
  "compare",
  "ai",
];
